[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache_forge"

# Compiler settings
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200

# Gas reporting
gas_reports = ["*"]

# Testing settings
verbosity = 2
fuzz_runs = 1000

[profile.ci]
fuzz_runs = 10_000
verbosity = 4

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
localhost = "http://localhost:8545"
mainnet = "${ETH_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" } 