name: BuildFair CD

on:
  push:
    branches:
      - main

jobs:
  whitepaper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base
      - name: Build
        working-directory: whitepaper
        run: |
          pdflatex main.tex
          mv main.pdf ../buildfair.pdf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }} ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: Upload Whitepaper
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./buildfair.pdf
          asset_name: buildfair.pdf
          asset_content_type: application/pdf

  contract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: contract
        run: |
          npm install
      - name: Build
        working-directory: contract
        run: |
          npx hardhat compile
      - name: Lint
        working-directory: contract
        run: |
          npx hardhat lint
      - name: Test
        working-directory: contract
        run: |
          npx hardhat test

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: buildfair-app
        run: |
          npm install -g pnpm
          pnpm install
      - name: Lint
        working-directory: buildfair-app
        run: |
          pnpm lint
